### ISSUE TITLE
Check command line please...

### ISSUE THREAD

**Issue by ctrlbru** [TheZ3ro/apk2java-linux#1]
Try ./apk2java --help to have your current folder nuked........ luckily it was the apk2java folder (it was able to complete delete itself from the hdd).

Console output follows

dario@ivymint /opt/apk2java $ ./apk2java --help
[ E ] Select a valid .apk file!

apk2java Linux - Author: Davide 'TheZero' Silvetti
Usage: ./apk2java [smali] <file>.apk
 Write 'smali' for disassemble .dex source code

---

*\*          Convert 'apk' to 'jar'         **

---

dex2jar /opt/apk2java/ -> -dex2jar.jar
java.io.IOException: File '/opt/apk2java' exists but is a directory
    at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:50)
    at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:40)
    at com.googlecode.dex2jar.reader.DexFileReader.<init>(DexFileReader.java:240)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:174)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:34)

---

*\*    Remove if any 'src' folder exists    **

---

---

*\*    Create 'src' and 'class' folders     **

---

---

*\*     Expand, delete the 'jar' file       **

---

ls: impossibile accedere a /opt/apk2java/*.jar: File o directory non esistente

---

*\*        Decompiling class files          **

---

---

*\* Delete .class files and 'class' folder  **

---

---

*\*      Extract, fix resource files        **

---

Input file (/opt/apk2java/) was not found or was not readable.

---

*\*       Create the Eclipse Project        **

---

rm: impossibile rimuovere "/opt/apk2java/": Permesso negato
unzip:  cannot find or open /opt/apk2java/tool/eclipseproject.zip, /opt/apk2java/tool/eclipseproject.zip.zip or /opt/apk2java/tool/eclipseproject.zip.ZIP.
cp: impossibile eseguire stat di "./src": File o directory non esistente
./apk2java: riga 176: cd: ./other: File o directory non esistente
cp: "./" e "/opt/apk2java/." sono lo stesso file
cat: /opt/apk2java//AndroidManifest.xml: File o directory non esistente
sed: impossibile leggere /opt/apk2java//.project: File o directory non esistente

---

*\*            Clean temp folder            **

---

rm: impossibile rimuovere "./src": File o directory non esistente
rm: impossibile rimuovere "./other": File o directory non esistente

---

*\*            Process complete             **

---

**Comment by TheZ3ro** [comment]
I will check, and I will also update the Decompiler, 'cause Jad is obsolete.
It will take some time because I'm busy ;)

**Comment by TheZ3ro** [comment]
Code rewrited in python. External tool updated. :)
